routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'CustomerController@index')->name('customers');

Route::group(['prefix' => 'customer'], function () {
    Route::get('/{id}', 'CustomerController@show');
    Route::post('/invoice/{id}', 'CustomerController@invoice');
});

Route::get('/invoices', 'InvoiceController@index')->name('invoices');

app/Agreement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @property string $customer_id
 * @property string $amount
 * @property string $type
 *
 * @package App
 */
class Agreement extends Model
{
    const TYPE_WEEKLY = 'weekly';
    const TYPE_MONTHLY = 'monthly';

    protected $fillable = [
        'unit_price', 'type'
    ];


    public function invoices()
    {
      return $this->hasMany(Invoice::class);
    }

    public function customer()
    {
      return $this->hasOne(Customer::class);
    }

    public function getTypeDaysAttribute()
    {
      if($this->type == self::TYPE_WEEKLY) return 7;
      if($this->type == self::TYPE_MONTHLY) return 30;
      return 0;
    }

}

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @property string $name
 * @property Agreement $agreement
 *
 * @package App
 */
class Customer extends Model
{
    protected $fillable = [
        'name', 'agreement_id'
    ];

    public function getNumberAttribute()
    {
        return 'C'.str_pad($this->id,8,'0',STR_PAD_LEFT);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function agreement()
    {
        return $this->belongsTo(Agreement::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function deliveries()
    {
        return $this->hasMany(Delivery::class);
    }
}

app/Delivery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Delivery extends Model
{
    protected $fillable = [
        'delivered_at',
        'count',
        'customer_id'
    ];


    public function customer()
    {
      return $this->belongsTo(Customer::class);
    }
}

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @property string $invoice_no
 * @property string $invoice_due_at
 * @property string $amount
 *
 * @package App
 */
class Invoice extends Model
{
    protected $fillable = [
        'agreement_id',
        'invoice_no',
        'invoice_due_at',
        'amount'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'invoice_due_at'
    ];


    public function agreement()
    {
      return $this->belongsTo(Agreement::class);
    }

    public function getCustomerAttribute()
    {
      return isset($this->agreement->customer) ? $this->agreement->customer : NULL;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\Invoice;
use App\Delivery;
use Carbon\Carbon;


/**
* I choose to respect the given architecture, or the lack here of, as stated in the Assignment notes.
* Best practice to only let classes in the Http folder handle responsibility concerning requests(routing, validation, request in out)
* Have dedicated classes for all business logic (Services) and classes dedicated to db and eloquent (Repositories)
* Dependency inject these into controller classes where needed, and let them handle all the logic not concerning the request.
*
* I also think the model classes should be organized in folder instead off app root
*/

class CustomerController extends Controller
{

    public function index()
    {
        $customers = Customer::all();

        //use helpers instead of importing facade - cleaner
        return view('customers', compact('customers'));
    }

    public function show($id)
    {
        $customer = Customer::findOrFail($id);
        $invoices = $customer->agreement->invoices;

        return view('customer', compact('customer', 'invoices'));
    }

    public function invoice($id)
    {


        //eager load agreement relation
        $customer = Customer::with(['agreement'])->findOrFail($id);

        //normally i would'nt have this kind of logic in a controller method as stated in the comments for the class
        $invoice = $this->createInvoiceFromCustomer($customer);

        //basic error handling
        if(!$invoice){
          return back()->withErrors(['An error has occurred trying to invoice customer']);
        }

        //no need to redirect -> re-route and bootstrap everything all over again. Just call the method directly.
        return $this->show($id);
    }

    public static function createInvoiceFromCustomer(Customer $customer)
    {
      $now = Carbon::now();

      //get delivery count sum based on users agreement period
      $deliveriesCountSum = Delivery::where('customer_id', $customer->id)
                                    ->whereDate('delivered_at', '>=', $now->subDay($customer->agreement->type_days)->format('Y-m-d'))
                                    ->sum('count');

      $invoiceAmount = $deliveriesCountSum * $customer->agreement->unit_price;

      //create invoice
      $invoice = Invoice::create([
        'agreement_id' => $customer->agreement->id,
        'invoice_no' => $now->timestamp, // could also just be the unique id
        'amount' => $invoiceAmount,
        'invoice_due_at' => $now->addDay(14)
      ]);

      return $invoice;

    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Invoice;
use Illuminate\Support\Facades\View;

class InvoiceController
{
    public function index()
    {
        $invoices = Invoice::with('agreement', 'agreement.customer')->get();
        return view('invoices', compact('invoices'));
    }

}

resources/views/customer.blade.php
@extends('layout')
<?php /** @var $customer \App\Customer  */ ?>
@section('content')
    <h2>{{$customer->name}}</h2>

    <div class="row">
      <div class="col-md-6">
        <div class="mb-2">DKK{{$customer->agreement->amount}} {{$customer->agreement->type}}</div>
      </div>
      <div class="col-md-6">
        <form method="post" action="/customer/invoice/{{$customer->id}}">
            {{ csrf_field() }}
            <input type="submit" class="btn btn-success float-right" value="Invoice customer" />
        </form>
      </div>
    </div>


    @if($errors->any())
    <h4 class="pt-4 text-danger">{{$errors->first()}}</h4>
    @endif

    <div class="pt-4">
      @include('invoices_table')
    </div>


@endsection

resources/views/customers.blade.php
@extends('layout')
<?php /** @var $customers \App\Customer[]  */ ?>
@section('content')
    <h2>Customers</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Agreement</th>
            </tr>
            </thead>
            <tbody>
            @foreach($customers as $customer)
            <tr>
                <td><a href="/customer/{{ $customer->id }}">{{ $customer->number }}</a></td>
                <td>{{ $customer->name }}</td>
                <td>{{ $customer->agreement->type }} DKK{{ $customer->agreement->amount }}</td>
            </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/invoices.blade.php
@extends('layout')
<?php /** @var $invoices \App\Invoice[]  */ ?>
@section('content')
    <h2>Invoices</h2>
    <div class="table-responsive">
      @include('invoices_table')
    </div>
@endsection

resources/views/invoices_table.blade.php
<table class="table table-striped">
    <thead>
    <tr>
        <th>#</th>
        <th>Due</th>
        <th>Amount</th>
        @if(!isset($customer))
          <th>Customer</th>
        @endif

    </tr>
    </thead>
    <tbody>
    @foreach($invoices as $invoice)
    <tr>
        <td>{{ $invoice->invoice_no}}</td>
        <td>{{ $invoice->invoice_due_at }}</td>
        <td>{{ $invoice->amount}}</td>
        @if(!isset($customer))
        <td>
          <a href="/customer/{{$invoice->customer->id}}">{{$invoice->customer->name}}</a>
        </td>
        @endif

    </tr>
    @endforeach
    </tbody>
</table>

resources/views/layout.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>Laravel</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>

<body>


  <div id="app">

    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-primary mb-3">
      <div class="flex-row d-flex">
        <button type="button" class="navbar-toggler mr-2 " data-toggle="offcanvas" title="Toggle responsive left sidebar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#" title="Free Bootstrap 4 Admin Template">Obviux Assignment</a>
      </div>
    </nav>

    <div class="container-fluid" id="main">
      <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-md-3 col-lg-2 sidebar-offcanvas bg-light pl-0 h-100" id="sidebar" role="navigation">
          <ul class="nav flex-column sticky-top pl-0 pt-5 mt-4">
            <li class="nav-item">
              <a class="nav-link" {{ ( (Route::currentRouteName() == 'customers') ? 'id=active_menu' : '') }}
              href="/">Customers </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" {{ ( (Route::currentRouteName() == 'invoices') ? 'id=active_menu' : '') }}
              href="/invoices">Invoices</a>
            </li>
          </ul>
        </div>
        <!--/col-->

        <div class="col main pt-5  h-100">
          <div class="container mt-4">
            @yield('content')
          </div>
        </div>

      </div>

    </div>

  </div>

  <script src="{{ mix('/js/app.js') }}"></script>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <!-- These are already loaded and compiled in app.js -->
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script> -->


</body>

</html>